### ISSUE TITLE
icon is not set

### ISSUE THREAD

**Issue by tobias-d-oe** [b-jesch/service.kn.switchtimer#1]
Used Confluence and VU+ PVR Addon. 
I've added a Timer and integrated the SkinStrings.
Informations like t0:channel, t0:title, t0:date are displayed correct, but t0:icon has no value.
I'm using version  1.0.12.

**Comment by b-jesch** [comment]
Have a look that the line with "<onclick>RunScript(service.kn.switchtimer,action=add,channel=$INFO[ListItem.ChannelName],icon=$INFO[ListItem.Icon],date=$INFO[ListItem.Date],title=$INFO[ListItem.Title])</onclick>" is not split into 2 lines of source code in your .xml. The line above is splitted near "Ic on" in the Readme so this could be a copy and paste failure. This is happened to me too...

The addon reads the label at the beginning of the epg line so if there isn't an icon the property will be empty.

**Comment by tobias-d-oe** [comment]
Problem is solved, thank you!
