### ISSUE TITLE
Offset for channel switching

### ISSUE THREAD

**Issue by h3ti** [b-jesch/service.kn.switchtimer#10]
Hi,

It would be nice if there was an option to specify an offset in minutes or seconds, so that the addon switches to the channel (eg. 2 minutes) before the TV show starts. I noticed that some shows started before the given time in the EPG, so that I missed the first minute(s).

**Comment by b-jesch** [comment]
I could this built in into settings, but this is a global value then (applies to all timers).

**Comment by h3ti** [comment]
👍

**Comment by b-jesch** [comment]
Has been implemented yet. Also there is a list of switchtimers now, where you can select and delete a timer directly. Accessible via context menu or addon selection.
