### ISSUE TITLE
recurring timer

### ISSUE THREAD

**Issue by rigid** [b-jesch/service.kn.switchtimer#4]
It would be awesome if this extension could mimic the normal recording-timer a bit more (just without recording).
I.e. support recurring timers (daily, weekly, etc.) or even title string matching.
This way, timers could be added once for a tv-series and cover all episodes.

**Comment by b-jesch** [comment]
No, this isn't possible. This addon get his data from the PVR-OSD directly via info strings. There is no access to the EPG database or similar. There are also no future plans to implement that.

Regards
