### ISSUE TITLE
Date/Time or Timer could not be calculated

### ISSUE THREAD

**Issue by kmarty** [b-jesch/service.kn.switchtimer#8]
Hi,
there is a bug which ends with $SUBJ.
Log:
`21:34:31.537 T:123145450418176   ERROR: [service.kn.switchtimer]: Couldn't parse date: 30.4.2017 21:40`

Possibly useful "debug":
df = %-d.%-m.%Y
tf = ['%H', '%M', '%S']
strptime() -> ValueError: '-' is a bad directive in format '%-d.%-m.%Y'

My (ugly) hack is to change line 57 from:
`df = xbmc.getRegion('dateshort')`
to:
`df = xbmc.getRegion('dateshort').replace('%-','%')`
which works to me but I don't think it is correct way to manipulate with dateformat.
(I could change date format to "%d.%m.%Y" in whole Kodi, of course. But normal regional date format to me is day and month without zero-padding).

**Comment by b-jesch** [comment]
Hi,

It seems that it is simply a bug in the xbmc module. xbmc.getRegion should provide the correct format like '%d-%m-%Y' or %d.%m.%Y' or whatelse. Possibly I change the date/datetime routines to datutil module which is much more flexible than the old ones.

Please tell me what your settings are (timezone, timeformat). Also I would provide a test version to you where you can check if its working okay. If so, I'll release an updated version of the addon later.

Thank You!

**Comment by b-jesch** [comment]
Could confirm that xbmc.getRegion returns an ugly string when format string is set to '1.5.2017' within kodi.

**Comment by b-jesch** [comment]
@kmarty try this out. Use 'install from zip' because there's dependency from script.module.dateutil which has to be installed.

[service.kn.switchtimer.zip](https://github.com/b-jesch/service.kn.switchtimer/files/967573/service.kn.switchtimer.zip)

**Comment by kmarty** [comment]
That ugly format seems to be correct date format for str**f**time() _(C library)_. Unfortunately it is plaform specific (on MS Windows you have to use `#` instead of `-`).

Anyway, your dateutil version works. Thank you.

**Comment by b-jesch** [comment]
For this moment I have another PR in queue of kodi. If that is done I'll submit the new version to kodi.tv. The german repos (kodinerds, saXBMC) are already updated.
